version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=parfume-erp
      - POSTGRES_PASSWORD=parfume-erp
      - POSTGRES_DB=parfume-erp
    ports:
      - "5432:5432"
